### ISSUE TITLE
Make possible to handle connection and socket errors

### ISSUE THREAD

**Issue by ribizli** [hbenl/mpc-js-core#4]
Maybe the [issue](https://github.com/hbenl/mpc-js-node/issues/1) belongs to this repo?

**Comment by ribizli** [comment]
Or if the connection is lost during the session:
```
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:305:12)
    at TcpSocketWrapper.send (C:\work\DAS\workspace\das-server\node_modules\mpc-js\lib\socketWrapper.js:17:21)
```

**Comment by ribizli** [comment]
I'd also like to implement a connection retry logic, have you any suggestion how to do it?

**Comment by hbenl** [comment]
See [this comment](https://github.com/hbenl/mpc-js-node/issues/1#issuecomment-320288990).

To retry connecting, you should call `mpc.disconnect()` and then `mpc.connectTCP(...)` again.
But the more difficult part is probably making sure that this retry logic doesn't run amok - reconnection attempts should be delayed, maybe it should give up after a certain number after retries, etc.

**Comment by ribizli** [comment]
Let me share our connection retry logic using the `retry` npm module.
(The retry settings is not configured in this example; we use `forever: true`)

``` typescript
import { MPC } from 'mpc-js';
import { operation, RetryOperation } from 'retry';

const mpc = new MPC();
export default mpc;
let connecting = false;

export function connectMpc() {

  return new Promise<void>((res, rej) => {

    connecting = true;
    let retryOperation = operation();

    retryOperation.attempt(i => {
      console.log(`MPC connection attempt ${i}`);
      mpc.connectTCP(env.mpdHost, env.mpdPort)
        .then(() => {
          connecting = false;
          res();
        })
        .catch(e => {
          if (!retryOperation.retry(e)) {
            connecting = false;
            rej(retryOperation.mainError());
          }
        });
    });
  });
}

mpc.on('ready', () => {
  console.log('MPC ready');
  attachHandlers(mpc);
});

mpc.on('socket-error', connectionLost);
mpc.on('socket-end', connectionLost);

function connectionLost(e?: any) {
  if (e) {
    console.warn(`MPC connection error: ${e.message}`)
  } else {
    console.warn('MPD closed the connection');
  }
  mpc.disconnect();
  if (!connecting) connectMpc();
}

```
